name: Stoplight Admin
on:
  push:
    branches: [master]
  pull_request:
    types: [
      synchronize, # PR was updated
      opened,      # PR was open
      reopened     # PR was closed and is now open again
    ]

jobs:
  RSpec:
    name: RSpec 💚
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.2', '3.3', '3.4' ]

    services:
      redis:
        image: redis:7.2
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        id: rspec
        run: bundle exec rspec
